---
title: "AVO Step 2: Storm Events"
author: "Anna Fryjoff-Hung"
date: "October 6, 2018"
output: html_notebook
---

#Load Required Packages
```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(rvest)
library(readr)
```


#Load Combined PT/WSE/Storage Dataset
```{r}

```

#Filtering for Storm Events by Threshold and Assigning Event Codes
```{r}

#Create threshold to find days with precip events
threshold <- y %>% 
  filter(precip_event_cm > 0.0) %>%
  group_by(Date) %>%
  mutate(count = n())

#Create vector of unique dates to identify storm events 
storm_days <- unique(threshold$Date)
storm_days <- as_tibble(storm_days)
names(storm_days)[1] <- "Date"

#filter pond data to storm events
pond_storms <- semi_join(y, storm_days, by = "Date")
# Create Storm Event Groupings based on consecutive days https://stackoverflow.com/questions/37342412/r-find-dates-consecutive 
pond_storms$storm_event <- cumsum(c(1, diff.Date(pond_storms$Date)) >= 2)
pond_storms

write.csv(pond_storms, file = "output/pond_storms.csv")

 storm_stats <- pond_storms %>% 
  group_by(storm_event) %>% 
  summarise(precip_mm = (max(precip_acc_cm)-min(precip_acc_cm))*10, vol_gain = (max(VOLUME)-min(VOLUME)), start_date = min(Date), end_date = max(Date))
 
 storm_stats$duration <- paste(storm_stats$start_date, storm_stats$end_date, sep = "-")
 write.csv(storm_stats, file = "output/storm_stats.csv")
```

#Add more columns to stormstats
# Connect with chunk above!!!
```{r}
s <- read.csv("output/storm_stats.csv") %>% 
  mutate(pond_vol_gain_acft = vol_gain*0.000810714, 
         vol_gain_pct_pond = 100*(vol_gain/79525.89), 
         vol_gain_pct_catch = 100*(vol_gain/(703367.5*0.001*precip_mm))) %>% 
  rename(pond_vol_gain_m3 = vol_gain) %>% 
  mutate_if(is.numeric, round, 2) 
s

write_csv(s, "output/20181025_storm_stats.csv")

t <- s %>% 
  filter(precip_mm>1)

write_csv(t, "output/20181025_storm_stats_filterprecip.csv")

u <- t %>% 
  filter(vol_gain_pct_pond>1)
  
write_csv(u, "output/20181025_storm_stats_filterpctpond.csv")
 
```


#Parse Out Storm Event Tables
```{r}
#https://stackoverflow.com/questions/13629659/efficient-way-to-output-subset-of-data-frame-based-on-column
# http://rprogramming.net/write-csv-in-r/
## Need to figure out how to write to output folder
storm_tables <- function(storm_event) {
  write.csv(pond_storms[pond_storms$storm_event == storm_event, ]
              , file = paste0("storm_event_", storm_event, ".csv")
              )
}

lapply(unique(pond_storms$storm_event), storm_tables)

```