---
title: "AVO_Precip_WSE"
output: html_notebook
---

Load required packages
```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(rvest)
library(readr)
library(grid)
library(sharpshootR)
library(gplots)
library(CDECRetrieve)
```
Load Precip data 
```{r}
#x <- read_csv("data/AVO_CDECprecip_1718.csv")

x <- cdec_query("ucm", 2, dur_code = "E", start_date = "2017-11-06", end_date = "2018-07-23")

#Edit columns
#x$DateTime <- as.POSIXct(x$ACTUAL_DATE)

#Calculate event data from accumulated data 
#Create lag 
x$lag <- lag(x$parameter_value, k = 1)

#Difference to get precip events in cm 
x$precip_event_cm <- (x$parameter_value-x$lag)*2.54

#Convert accumulated precip to cm
x$precip_acc_cm <- (x$parameter_value)*2.54

#Change column name
names(x)[3]<-"DateTime"

```


Load Processed Inflow Data
```{r}
inflow <- read_csv("data/AVO_Inflows_15min.csv")
```
Join Inflow and Precip Data
```{r}
y <- inner_join(inflow, x, by = "DateTime")

#Create columns for depth in different units
y$Depth_m <- (y$WSE-120.77)
y$Depth_cm <- (y$WSE-120.77)*100

#Calculate day to day % change in precip

# Percent Change for Precip
#https://stackoverflow.com/questions/48196552/calculate-percentage-change-in-r-using-dplyr 
y$precip_pct_chg <- (y$precip_acc_cm/lag(y$precip_acc_cm) - 1) * 100
# Percent of Total
y$precip_pct_tot <- (y$precip_acc_cm/25.5778) * 100

#Percent Change for Pond



```


Plot Cumulative Precip
```{r}
# https://thepracticalr.wordpress.com/2016/08/30/2-y-axis-plotting/ 

png("figs/depth_precip.png", width = 800, height = 600)

par(mar = c(5, 5, 3, 5))
plot(y$DateTime, y$Depth_cm, type ="l", ylab = "Depth (cm)", main = "Depth vs. Cumulative Precip", xlab = "Date", col = "deepskyblue")
par(new = TRUE)
plot(y$DateTime, y$precip_acc_cm, type ="l", xaxt = "n", yaxt = "n", ylab = "", xlab = "", col = "darkblue", lty = 2)
axis(side = 4)
mtext("Precip (cm)", side = 4, line = 3)
legend("topleft", c("Depth (cm)", "Precip (cm)"),
       col = c("deepskyblue", "darkblue"), lty = c(1, 2))

dev.off()
```

Plot Precip Percents

```{r}
png("figs/precip_change.png", width = 800, height = 600)

par(mar = c(5, 5, 3, 5))
plot(y$DateTime, y$precip_pct_chg, type ="l", ylab = "% Change", main = "Changes in Precip", xlab = "Date", col = "deepskyblue")
par(new = TRUE)
plot(y$DateTime, y$precip_pct_tot, type ="l", xaxt = "n", yaxt = "n", ylab = "", xlab = "", col = "darkblue", lty = 2)
axis(side = 4)
mtext("% Total", side = 4, line = 3)
legend("right", c("% Change", "% Total"),
       col = c("deepskyblue", "darkblue"), lty = c(1, 2))

dev.off()
```


```{r}
# p <- ggplot(y, aes(x = DateTime))
#   p <- p + geom_line(aes(y = WSE), lty = 1) #+ coord_cartesian(ylim=c(120, 125))
#   
#   # adding the precip, transformed to match roughly the range of the WSE
#   p <- p + geom_line(aes(y = precip_acc_cm, colour = "Precipitation (cm)"), lty = 3)
#   p
# 
#   # now adding the secondary axis, following the example in the help file ?scale_y_continuous
#   # and, very important, reverting the above transformation
#   p <- p + scale_y_continuous(sec.axis = sec_axis(~., name = "Precipitation (cm)"))
# 
#   # modifying colours and theme options
#   p <- p + scale_colour_manual(labels = c("Water Surface Elevation (cm)", "Precipitation (cm)"), values = c("blue","red"))
#   p <- p + labs(y = "WSE",
#                 x = "Date",
#                 colour = NULL)
#   p <- p + ggtitle("Change in WSE vs. Precip")
#   p <- p + theme(plot.title = element_text(hjust = 0.5))
#   p  <- p + theme(legend.position = c(0.85, 0.85))
#   p
```
```{r}
# p1 <- ggplot(y, aes(x = DateTime))
#   p1 <- p1 + geom_line(aes(y = WSE), lty = 1) 
#   p1
#   
# p2 <- ggplot(y, aes(x = DateTime))
#   p2 <- p2 + geom_line(aes(y = precip_cm), lty = 1) 
#   p2
# 
# grid.newpage()
# ggsave("wse_precip.jpg", path = "E:/AVOCET/AVOCET_GIT/figs", plot = grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2), size = "last")))
```

